INSERT INTO users VALUES (DEFAULT, 'a', 'a');
INSERT INTO subjects VALUES (DEFAULT, 1, 'a');
INSERT INTO cards VALUES (DEFAULT, 1, 'a', 'a', 1);
INSERT INTO cards VALUES (DEFAULT, 1, 'b', 'b', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'c', 'c', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'd', 'd', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'e', 'e', 2);
INSERT INTO cards VALUES (DEFAULT, 1, 'f', 'f', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'g', 'g', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'h', 'h', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'i', 'i', null);
INSERT INTO cards VALUES (DEFAULT, 1, 'j', 'j', null);
