\echo\;
\echo -                        users:\;
\echo\;
select * from users ORDER BY id;
\echo\;
\echo -                        subjects:\;
\echo\;
select * from subjects ORDER BY id;
\echo\;
\echo -                        cards:\;
\echo\;
select * from cards ORDER BY id;
\echo\;
\echo -                        training_sessions:\;
\echo\;
select * from training_sessions ORDER BY id;
\echo\;
\echo -                        card_results:\;
\echo\;
select * from card_results ORDER BY id;
\echo\;
\echo -                        card_schedules:\;
\echo\;
select * from card_schedules ORDER BY id;
\echo\;
\echo\;