INSERT INTO users VALUES (DEFAULT, 'shared', 'shared');
INSERT INTO subjects VALUES (DEFAULT, 1, 'spanish101');
INSERT INTO cards VALUES (DEFAULT, '1', 1, 'que', 'that', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '2', 1, 'de', 'of, from', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '3', 1, 'no', 'no', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '4', 1, 'a', 'to', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '5', 1, 'la', 'the feminine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '6', 1, 'el', 'the masculine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '7', 1, 'es', 'he is, she is, it is', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '8', 1, 'y', 'and', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '9', 1, 'en', 'in, on, at', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '10', 1, 'lo', 'it, him', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '11', 1, 'un', 'a, an masculine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '12', 1, 'una', 'a, an feminine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '13', 1, 'por', 'for, by, through', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '14', 1, 'qué', 'what how', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '15', 1, 'me', 'me, myself', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '16', 1, 'te', 'you', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '17', 1, 'los', 'the masculine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '18', 1, 'se', 'himself, herself, itself', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '19', 1, 'con', 'with', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '20', 1, 'para', 'for, to', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '21', 1, 'mi', 'my', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '22', 1, 'está', 'he is, she is, it is', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '23', 1, 'si', 'if', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '24', 1, 'bien', 'well, good', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '25', 1, 'pero', 'but', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '26', 1, 'yo', 'I', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '27', 1, 'eso', 'that', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '28', 1, 'las', 'the feminine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '29', 1, 'sí', 'yes', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '30', 1, 'su', 'his, her, its', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '31', 1, 'tu', 'your', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '32', 1, 'aquí', 'here', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '33', 1, 'del', 'of the, from the, in the', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '34', 1, 'al', 'to the', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '35', 1, 'como', 'how, as, like', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '36', 1, 'le', 'him, her, formal you', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '37', 1, 'más', 'more', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '38', 1, 'esto', 'this masculine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '39', 1, 'ya', 'already', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '40', 1, 'todo', 'everything', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '41', 1, 'esta', 'this one feminine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '42', 1, 'vamos', 'let’s go, come on', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '43', 1, 'muy', 'very', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '44', 1, 'hay', 'there is', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '45', 1, 'ahora', 'now', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '46', 1, 'algo', 'something', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '47', 1, 'estoy', 'I am', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '48', 1, 'tengo', 'I have', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '49', 1, 'nos', 'us', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '50', 1, 'tú', 'you', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '51', 1, 'nada', 'nothing', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '52', 1, 'cuando', 'when', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '53', 1, 'ha', 'he has, she has, it has', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '54', 1, 'este', 'this one masculine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '55', 1, 'sé', 'I know', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '56', 1, 'estás', 'you are', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '57', 1, 'así', 'like this', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '58', 1, 'puedo', 'I can', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '59', 1, 'cómo', 'how', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '60', 1, 'quiero', 'I want', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '61', 1, 'sólo', 'only, just', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '62', 1, 'soy', 'I am', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '63', 1, 'tiene', 'he has, she has, it has', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '64', 1, 'gracias', 'thank you', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '65', 1, 'o', 'or', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '66', 1, 'él', 'he', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '67', 1, 'bueno', 'good', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '68', 1, 'fue', 'he was, she was, it was', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '69', 1, 'ser', 'to be', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '70', 1, 'hacer', 'to do, to make', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '71', 1, 'son', 'they are', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '72', 1, 'todos', 'all of us, all of them', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '73', 1, 'era', 'he was, she was, it was', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '74', 1, 'eres', 'you are', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '75', 1, 'vez', 'time', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '76', 1, 'tienes', 'you have', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '77', 1, 'creo', 'I believe', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '78', 1, 'ella', 'she', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '79', 1, 'he', 'I have', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '80', 1, 'ese', 'that one', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '81', 1, 'voy', 'I go', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '82', 1, 'puede', 'he can, she can, it can', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '83', 1, 'sabes', 'you know', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '84', 1, 'hola', 'hello', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '85', 1, 'sus', 'his, her', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '86', 1, 'porque', 'because', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '87', 1, 'Dios', 'God', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '88', 1, 'quién', 'who', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '89', 1, 'nunca', 'never', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '90', 1, 'dónde', 'where', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '91', 1, 'quieres', 'you want', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '92', 1, 'casa', 'house', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '93', 1, 'favor', 'favor', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '94', 1, 'esa', 'that one feminine', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '95', 1, 'dos', 'two', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '96', 1, 'tan', 'so', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '97', 1, 'señor', 'mister', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '98', 1, 'tiempo', 'time', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '99', 1, 'verdad', 'truth', null, 0, 0);
INSERT INTO cards VALUES (DEFAULT, '100', 1, 'estaba', 'I was', null, 0, 0);
